services:
  server:
    build: .
    container_name: backend
    ports: 
      - 8080:8080
    tty: true
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    # "echo 'Migrating CSAT database' &&
    # ./tern migrate -c db/migrations/csat/tern.conf -m db/migrations/csat/ &&
    # echo 'Finished CSAT database migrations' &&
    command: >
        sh -c "echo 'Migrating main database' &&
              ./tern migrate -c db/migrations/public/tern.conf -m db/migrations/public/ &&
              echo 'Finished main database migrations' &&
              echo 'Starting backend' &&
              ./yablonka-backend"
    env_file:
      - ./config/.env
    volumes:
      - ./img/:/img/
  
  db:
    image: postgres:latest
    container_name: database
    env_file:
      - ./config/.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
