services:
  server:
    build: .
    container_name: backend
    ports: 
      - 8080:8080
    tty: true
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    command: >
        sh -c "echo "Migrating" &&
              ./tern migrate -c db/migrations/tern.conf -m db/migrations/ &&
              echo 'Finished migrations' &&
              echo 'Starting backend' &&
              ./yablonka-backend"
    env_file:
      - ./config/.env
    volumes:
      - img/:img/
  
  db:
    image: postgres:latest
    container_name: database
    env_file:
      - ./config/.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
