// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.1
// source: csrf/api/csrf.proto

package csrf_microservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_OK                    ErrorCode = 0
	ErrorCode_COULD_NOT_BUILD_QUERY ErrorCode = 1
	ErrorCode_TOKEN_NOT_GENERATED   ErrorCode = 2
	ErrorCode_CSRF_EXPIRED          ErrorCode = 3
	ErrorCode_CSRF_NOT_FOUND        ErrorCode = 4
	ErrorCode_CSRF_NOT_CREATED      ErrorCode = 5
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "OK",
		1: "COULD_NOT_BUILD_QUERY",
		2: "TOKEN_NOT_GENERATED",
		3: "CSRF_EXPIRED",
		4: "CSRF_NOT_FOUND",
		5: "CSRF_NOT_CREATED",
	}
	ErrorCode_value = map[string]int32{
		"OK":                    0,
		"COULD_NOT_BUILD_QUERY": 1,
		"TOKEN_NOT_GENERATED":   2,
		"CSRF_EXPIRED":          3,
		"CSRF_NOT_FOUND":        4,
		"CSRF_NOT_CREATED":      5,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_csrf_api_csrf_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_csrf_api_csrf_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_csrf_api_csrf_proto_rawDescGZIP(), []int{0}
}

type CSRFToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *CSRFToken) Reset() {
	*x = CSRFToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrf_api_csrf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRFToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRFToken) ProtoMessage() {}

func (x *CSRFToken) ProtoReflect() protoreflect.Message {
	mi := &file_csrf_api_csrf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRFToken.ProtoReflect.Descriptor instead.
func (*CSRFToken) Descriptor() ([]byte, []int) {
	return file_csrf_api_csrf_proto_rawDescGZIP(), []int{0}
}

func (x *CSRFToken) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CSRFData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ExpirationDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ExpirationDate,proto3" json:"ExpirationDate,omitempty"`
}

func (x *CSRFData) Reset() {
	*x = CSRFData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrf_api_csrf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRFData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRFData) ProtoMessage() {}

func (x *CSRFData) ProtoReflect() protoreflect.Message {
	mi := &file_csrf_api_csrf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRFData.ProtoReflect.Descriptor instead.
func (*CSRFData) Descriptor() ([]byte, []int) {
	return file_csrf_api_csrf_proto_rawDescGZIP(), []int{1}
}

func (x *CSRFData) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CSRFData) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

type UserID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint64 `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *UserID) Reset() {
	*x = UserID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrf_api_csrf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_csrf_api_csrf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_csrf_api_csrf_proto_rawDescGZIP(), []int{2}
}

func (x *UserID) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetupCSRFResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     ErrorCode `protobuf:"varint,1,opt,name=Code,proto3,enum=csrf.ErrorCode" json:"Code,omitempty"`
	Response *CSRFData `protobuf:"bytes,2,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *SetupCSRFResponse) Reset() {
	*x = SetupCSRFResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrf_api_csrf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupCSRFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupCSRFResponse) ProtoMessage() {}

func (x *SetupCSRFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csrf_api_csrf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupCSRFResponse.ProtoReflect.Descriptor instead.
func (*SetupCSRFResponse) Descriptor() ([]byte, []int) {
	return file_csrf_api_csrf_proto_rawDescGZIP(), []int{3}
}

func (x *SetupCSRFResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *SetupCSRFResponse) GetResponse() *CSRFData {
	if x != nil {
		return x.Response
	}
	return nil
}

type VerifyCSRFResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ErrorCode `protobuf:"varint,1,opt,name=Code,proto3,enum=csrf.ErrorCode" json:"Code,omitempty"`
}

func (x *VerifyCSRFResponse) Reset() {
	*x = VerifyCSRFResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrf_api_csrf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCSRFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCSRFResponse) ProtoMessage() {}

func (x *VerifyCSRFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csrf_api_csrf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCSRFResponse.ProtoReflect.Descriptor instead.
func (*VerifyCSRFResponse) Descriptor() ([]byte, []int) {
	return file_csrf_api_csrf_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyCSRFResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

type DeleteCSRFResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ErrorCode `protobuf:"varint,1,opt,name=Code,proto3,enum=csrf.ErrorCode" json:"Code,omitempty"`
}

func (x *DeleteCSRFResponse) Reset() {
	*x = DeleteCSRFResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrf_api_csrf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCSRFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCSRFResponse) ProtoMessage() {}

func (x *DeleteCSRFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csrf_api_csrf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCSRFResponse.ProtoReflect.Descriptor instead.
func (*DeleteCSRFResponse) Descriptor() ([]byte, []int) {
	return file_csrf_api_csrf_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCSRFResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

type GetLifetimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     ErrorCode            `protobuf:"varint,1,opt,name=Code,proto3,enum=csrf.ErrorCode" json:"Code,omitempty"`
	Response *durationpb.Duration `protobuf:"bytes,2,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *GetLifetimeResponse) Reset() {
	*x = GetLifetimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrf_api_csrf_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLifetimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLifetimeResponse) ProtoMessage() {}

func (x *GetLifetimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csrf_api_csrf_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLifetimeResponse.ProtoReflect.Descriptor instead.
func (*GetLifetimeResponse) Descriptor() ([]byte, []int) {
	return file_csrf_api_csrf_proto_rawDescGZIP(), []int{6}
}

func (x *GetLifetimeResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetLifetimeResponse) GetResponse() *durationpb.Duration {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_csrf_api_csrf_proto protoreflect.FileDescriptor

var file_csrf_api_csrf_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x73, 0x72, 0x66, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x73, 0x72, 0x66, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x73, 0x72, 0x66, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x09, 0x43, 0x53, 0x52,
	0x46, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5e, 0x0a, 0x08,
	0x43, 0x53, 0x52, 0x46, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x42, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x22, 0x1e, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x64, 0x0a, 0x11,
	0x53, 0x65, 0x74, 0x75, 0x70, 0x43, 0x53, 0x52, 0x46, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x63, 0x73, 0x72, 0x66, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x73, 0x72, 0x66, 0x2e,
	0x43, 0x53, 0x52, 0x46, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x39, 0x0a, 0x12, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x53, 0x52, 0x46,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x73, 0x72, 0x66, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x39, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x53, 0x52, 0x46, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x73, 0x72, 0x66, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x71, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x23, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x63, 0x73, 0x72, 0x66, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x83, 0x01, 0x0a, 0x09,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x55, 0x4c, 0x44, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x42,
	0x55, 0x49, 0x4c, 0x44, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13,
	0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x41,
	0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x53, 0x52, 0x46, 0x5f, 0x45, 0x58,
	0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x53, 0x52, 0x46, 0x5f,
	0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x43,
	0x53, 0x52, 0x46, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10,
	0x05, 0x32, 0xfd, 0x01, 0x0a, 0x0b, 0x43, 0x53, 0x52, 0x46, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x34, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x75, 0x70, 0x43, 0x53, 0x52, 0x46, 0x12, 0x0c,
	0x2e, 0x63, 0x73, 0x72, 0x66, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x17, 0x2e, 0x63,
	0x73, 0x72, 0x66, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x43, 0x53, 0x52, 0x46, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x53, 0x52, 0x46, 0x12, 0x0f, 0x2e, 0x63, 0x73, 0x72, 0x66, 0x2e, 0x43, 0x53, 0x52,
	0x46, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x18, 0x2e, 0x63, 0x73, 0x72, 0x66, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x53, 0x52, 0x46, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x53, 0x52, 0x46,
	0x12, 0x0f, 0x2e, 0x63, 0x73, 0x72, 0x66, 0x2e, 0x43, 0x53, 0x52, 0x46, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x1a, 0x18, 0x2e, 0x63, 0x73, 0x72, 0x66, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x53, 0x52, 0x46, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x63, 0x73, 0x72, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x3b, 0x63, 0x73, 0x72, 0x66, 0x5f, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_csrf_api_csrf_proto_rawDescOnce sync.Once
	file_csrf_api_csrf_proto_rawDescData = file_csrf_api_csrf_proto_rawDesc
)

func file_csrf_api_csrf_proto_rawDescGZIP() []byte {
	file_csrf_api_csrf_proto_rawDescOnce.Do(func() {
		file_csrf_api_csrf_proto_rawDescData = protoimpl.X.CompressGZIP(file_csrf_api_csrf_proto_rawDescData)
	})
	return file_csrf_api_csrf_proto_rawDescData
}

var file_csrf_api_csrf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_csrf_api_csrf_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_csrf_api_csrf_proto_goTypes = []interface{}{
	(ErrorCode)(0),                // 0: csrf.ErrorCode
	(*CSRFToken)(nil),             // 1: csrf.CSRFToken
	(*CSRFData)(nil),              // 2: csrf.CSRFData
	(*UserID)(nil),                // 3: csrf.UserID
	(*SetupCSRFResponse)(nil),     // 4: csrf.SetupCSRFResponse
	(*VerifyCSRFResponse)(nil),    // 5: csrf.VerifyCSRFResponse
	(*DeleteCSRFResponse)(nil),    // 6: csrf.DeleteCSRFResponse
	(*GetLifetimeResponse)(nil),   // 7: csrf.GetLifetimeResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 9: google.protobuf.Duration
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_csrf_api_csrf_proto_depIdxs = []int32{
	8,  // 0: csrf.CSRFData.ExpirationDate:type_name -> google.protobuf.Timestamp
	0,  // 1: csrf.SetupCSRFResponse.Code:type_name -> csrf.ErrorCode
	2,  // 2: csrf.SetupCSRFResponse.Response:type_name -> csrf.CSRFData
	0,  // 3: csrf.VerifyCSRFResponse.Code:type_name -> csrf.ErrorCode
	0,  // 4: csrf.DeleteCSRFResponse.Code:type_name -> csrf.ErrorCode
	0,  // 5: csrf.GetLifetimeResponse.Code:type_name -> csrf.ErrorCode
	9,  // 6: csrf.GetLifetimeResponse.Response:type_name -> google.protobuf.Duration
	3,  // 7: csrf.CSRFService.SetupCSRF:input_type -> csrf.UserID
	1,  // 8: csrf.CSRFService.VerifyCSRF:input_type -> csrf.CSRFToken
	1,  // 9: csrf.CSRFService.DeleteCSRF:input_type -> csrf.CSRFToken
	10, // 10: csrf.CSRFService.GetLifetime:input_type -> google.protobuf.Empty
	4,  // 11: csrf.CSRFService.SetupCSRF:output_type -> csrf.SetupCSRFResponse
	5,  // 12: csrf.CSRFService.VerifyCSRF:output_type -> csrf.VerifyCSRFResponse
	6,  // 13: csrf.CSRFService.DeleteCSRF:output_type -> csrf.DeleteCSRFResponse
	7,  // 14: csrf.CSRFService.GetLifetime:output_type -> csrf.GetLifetimeResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_csrf_api_csrf_proto_init() }
func file_csrf_api_csrf_proto_init() {
	if File_csrf_api_csrf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_csrf_api_csrf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRFToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csrf_api_csrf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRFData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csrf_api_csrf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csrf_api_csrf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupCSRFResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csrf_api_csrf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCSRFResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csrf_api_csrf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCSRFResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csrf_api_csrf_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLifetimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_csrf_api_csrf_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_csrf_api_csrf_proto_goTypes,
		DependencyIndexes: file_csrf_api_csrf_proto_depIdxs,
		EnumInfos:         file_csrf_api_csrf_proto_enumTypes,
		MessageInfos:      file_csrf_api_csrf_proto_msgTypes,
	}.Build()
	File_csrf_api_csrf_proto = out.File
	file_csrf_api_csrf_proto_rawDesc = nil
	file_csrf_api_csrf_proto_goTypes = nil
	file_csrf_api_csrf_proto_depIdxs = nil
}
