// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.1
// source: csat/api/csat_answer.proto

package csat_microservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_OK                    ErrorCode = 0
	ErrorCode_COULD_NOT_BUILD_QUERY ErrorCode = 1
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "OK",
		1: "COULD_NOT_BUILD_QUERY",
	}
	ErrorCode_value = map[string]int32{
		"OK":                    0,
		"COULD_NOT_BUILD_QUERY": 1,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_csat_api_csat_answer_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_csat_api_csat_answer_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_csat_api_csat_answer_proto_rawDescGZIP(), []int{0}
}

type NewCSATAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID     uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	QuestionID uint64 `protobuf:"varint,2,opt,name=QuestionID,proto3" json:"QuestionID,omitempty"`
	Rating     uint64 `protobuf:"varint,3,opt,name=Rating,proto3" json:"Rating,omitempty"`
}

func (x *NewCSATAnswer) Reset() {
	*x = NewCSATAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csat_api_csat_answer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewCSATAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCSATAnswer) ProtoMessage() {}

func (x *NewCSATAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_csat_api_csat_answer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCSATAnswer.ProtoReflect.Descriptor instead.
func (*NewCSATAnswer) Descriptor() ([]byte, []int) {
	return file_csat_api_csat_answer_proto_rawDescGZIP(), []int{0}
}

func (x *NewCSATAnswer) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *NewCSATAnswer) GetQuestionID() uint64 {
	if x != nil {
		return x.QuestionID
	}
	return 0
}

func (x *NewCSATAnswer) GetRating() uint64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ErrorCode `protobuf:"varint,1,opt,name=Code,proto3,enum=csat_microservice.ErrorCode" json:"Code,omitempty"`
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csat_api_csat_answer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csat_api_csat_answer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_csat_api_csat_answer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

var File_csat_api_csat_answer_proto protoreflect.FileDescriptor

var file_csat_api_csat_answer_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x73, 0x61, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x73, 0x61, 0x74, 0x5f,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63, 0x73,
	0x61, 0x74, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x5f, 0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x43, 0x53, 0x41, 0x54, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x22, 0x42, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1c, 0x2e, 0x63, 0x73, 0x61, 0x74, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x2a, 0x2e, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x55,
	0x4c, 0x44, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x5f, 0x51, 0x55, 0x45,
	0x52, 0x59, 0x10, 0x01, 0x32, 0x64, 0x0a, 0x11, 0x43, 0x53, 0x41, 0x54, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x20, 0x2e, 0x63, 0x73, 0x61, 0x74, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x53, 0x41, 0x54, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x1a, 0x21, 0x2e, 0x63, 0x73, 0x61, 0x74, 0x5f, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f,
	0x3b, 0x63, 0x73, 0x61, 0x74, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_csat_api_csat_answer_proto_rawDescOnce sync.Once
	file_csat_api_csat_answer_proto_rawDescData = file_csat_api_csat_answer_proto_rawDesc
)

func file_csat_api_csat_answer_proto_rawDescGZIP() []byte {
	file_csat_api_csat_answer_proto_rawDescOnce.Do(func() {
		file_csat_api_csat_answer_proto_rawDescData = protoimpl.X.CompressGZIP(file_csat_api_csat_answer_proto_rawDescData)
	})
	return file_csat_api_csat_answer_proto_rawDescData
}

var file_csat_api_csat_answer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_csat_api_csat_answer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_csat_api_csat_answer_proto_goTypes = []interface{}{
	(ErrorCode)(0),         // 0: csat_microservice.ErrorCode
	(*NewCSATAnswer)(nil),  // 1: csat_microservice.NewCSATAnswer
	(*CreateResponse)(nil), // 2: csat_microservice.CreateResponse
}
var file_csat_api_csat_answer_proto_depIdxs = []int32{
	0, // 0: csat_microservice.CreateResponse.Code:type_name -> csat_microservice.ErrorCode
	1, // 1: csat_microservice.CSATAnswerService.Create:input_type -> csat_microservice.NewCSATAnswer
	2, // 2: csat_microservice.CSATAnswerService.Create:output_type -> csat_microservice.CreateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_csat_api_csat_answer_proto_init() }
func file_csat_api_csat_answer_proto_init() {
	if File_csat_api_csat_answer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_csat_api_csat_answer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewCSATAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csat_api_csat_answer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_csat_api_csat_answer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_csat_api_csat_answer_proto_goTypes,
		DependencyIndexes: file_csat_api_csat_answer_proto_depIdxs,
		EnumInfos:         file_csat_api_csat_answer_proto_enumTypes,
		MessageInfos:      file_csat_api_csat_answer_proto_msgTypes,
	}.Build()
	File_csat_api_csat_answer_proto = out.File
	file_csat_api_csat_answer_proto_rawDesc = nil
	file_csat_api_csat_answer_proto_goTypes = nil
	file_csat_api_csat_answer_proto_depIdxs = nil
}
