// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package microservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CSATSAnswerServiceClient is the client API for CSATSAnswerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CSATSAnswerServiceClient interface {
	Create(ctx context.Context, in *NewCSATAnswer, opts ...grpc.CallOption) (*Error, error)
}

type cSATSAnswerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCSATSAnswerServiceClient(cc grpc.ClientConnInterface) CSATSAnswerServiceClient {
	return &cSATSAnswerServiceClient{cc}
}

func (c *cSATSAnswerServiceClient) Create(ctx context.Context, in *NewCSATAnswer, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := c.cc.Invoke(ctx, "/service.CSATSAnswerService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CSATSAnswerServiceServer is the server API for CSATSAnswerService service.
// All implementations must embed UnimplementedCSATSAnswerServiceServer
// for forward compatibility
type CSATSAnswerServiceServer interface {
	Create(context.Context, *NewCSATAnswer) (*Error, error)
	mustEmbedUnimplementedCSATSAnswerServiceServer()
}

// UnimplementedCSATSAnswerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCSATSAnswerServiceServer struct {
}

func (UnimplementedCSATSAnswerServiceServer) Create(context.Context, *NewCSATAnswer) (*Error, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCSATSAnswerServiceServer) mustEmbedUnimplementedCSATSAnswerServiceServer() {}

// UnsafeCSATSAnswerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CSATSAnswerServiceServer will
// result in compilation errors.
type UnsafeCSATSAnswerServiceServer interface {
	mustEmbedUnimplementedCSATSAnswerServiceServer()
}

func RegisterCSATSAnswerServiceServer(s grpc.ServiceRegistrar, srv CSATSAnswerServiceServer) {
	s.RegisterService(&CSATSAnswerService_ServiceDesc, srv)
}

func _CSATSAnswerService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCSATAnswer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSATSAnswerServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CSATSAnswerService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSATSAnswerServiceServer).Create(ctx, req.(*NewCSATAnswer))
	}
	return interceptor(ctx, in, info, handler)
}

// CSATSAnswerService_ServiceDesc is the grpc.ServiceDesc for CSATSAnswerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CSATSAnswerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.CSATSAnswerService",
	HandlerType: (*CSATSAnswerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CSATSAnswerService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "csat_answer.proto",
}
