// Code generated by MockGen. DO NOT EDIT.
// Source: P:\VK Образование\Web\Sem_2\Project\2023_2_yablonka\internal\storage\workspace.go
//
// Generated by this command:
//
//	mockgen.exe --source=P:\VK Образование\Web\Sem_2\Project\2023_2_yablonka\internal\storage\workspace.go --destination=./mocks/mock_storage/mock_workspace_storage.go --package=mock_storage
//
// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	context "context"
	reflect "reflect"
	dto "server/internal/pkg/dto"
	entities "server/internal/pkg/entities"

	gomock "go.uber.org/mock/gomock"
)

// MockIWorkspaceStorage is a mock of IWorkspaceStorage interface.
type MockIWorkspaceStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkspaceStorageMockRecorder
}

// MockIWorkspaceStorageMockRecorder is the mock recorder for MockIWorkspaceStorage.
type MockIWorkspaceStorageMockRecorder struct {
	mock *MockIWorkspaceStorage
}

// NewMockIWorkspaceStorage creates a new mock instance.
func NewMockIWorkspaceStorage(ctrl *gomock.Controller) *MockIWorkspaceStorage {
	mock := &MockIWorkspaceStorage{ctrl: ctrl}
	mock.recorder = &MockIWorkspaceStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkspaceStorage) EXPECT() *MockIWorkspaceStorageMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIWorkspaceStorage) Create(arg0 context.Context, arg1 dto.NewWorkspaceInfo) (*entities.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*entities.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIWorkspaceStorageMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIWorkspaceStorage)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockIWorkspaceStorage) Delete(arg0 context.Context, arg1 dto.WorkspaceID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIWorkspaceStorageMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIWorkspaceStorage)(nil).Delete), arg0, arg1)
}

// GetUserWorkspaces mocks base method.
func (m *MockIWorkspaceStorage) GetUserWorkspaces(arg0 context.Context, arg1 dto.UserID) (*[]entities.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWorkspaces", arg0, arg1)
	ret0, _ := ret[0].(*[]entities.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWorkspaces indicates an expected call of GetUserWorkspaces.
func (mr *MockIWorkspaceStorageMockRecorder) GetUserWorkspaces(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWorkspaces", reflect.TypeOf((*MockIWorkspaceStorage)(nil).GetUserWorkspaces), arg0, arg1)
}

// GetUsersInWorkspace mocks base method.
func (m *MockIWorkspaceStorage) GetUsersInWorkspace(arg0 context.Context, arg1 dto.WorkspaceID) (*dto.UsersAndRoles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersInWorkspace", arg0, arg1)
	ret0, _ := ret[0].(*dto.UsersAndRoles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersInWorkspace indicates an expected call of GetUsersInWorkspace.
func (mr *MockIWorkspaceStorageMockRecorder) GetUsersInWorkspace(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersInWorkspace", reflect.TypeOf((*MockIWorkspaceStorage)(nil).GetUsersInWorkspace), arg0, arg1)
}

// GetWithBoards mocks base method.
func (m *MockIWorkspaceStorage) GetWithBoards(arg0 context.Context, arg1 dto.WorkspaceID) (*entities.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithBoards", arg0, arg1)
	ret0, _ := ret[0].(*entities.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithBoards indicates an expected call of GetWithBoards.
func (mr *MockIWorkspaceStorageMockRecorder) GetWithBoards(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithBoards", reflect.TypeOf((*MockIWorkspaceStorage)(nil).GetWithBoards), arg0, arg1)
}

// Update mocks base method.
func (m *MockIWorkspaceStorage) Update(arg0 context.Context, arg1 dto.UpdatedWorkspaceInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIWorkspaceStorageMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIWorkspaceStorage)(nil).Update), arg0, arg1)
}
