// Code generated by MockGen. DO NOT EDIT.
// Source: P:\VK Образование\Web\Sem_2\Project\2023_2_yablonka\internal\storage\storages.go
//
// Generated by this command:
//
//	mockgen.exe --source=P:\VK Образование\Web\Sem_2\Project\2023_2_yablonka\internal\storage\storages.go --destination=./mocks/mock_storage/mock_storages_storage.go --package=mock_storage
//
// Package mock_storage is a generated GoMock package.
package mock_storage
