# config.yml

server:
  allowed_methods:
    - GET
    - POST
    - OPTIONS
  allowed_hosts:
    - localhost:8080
    - localhost:8081
    - 213.219.215.40:8080
    - 213.219.215.40:8081
  allow_credentials: true