basePath: /
host: localhost:8080
info:
  contact:
    email: kdanil01@mail.ru
    name: Глеб Макаренко
    url: https://vk.com/glibu_s
  description: Лучший сервис для слежкой за прогрессом над проектом.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: LA TABULA API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      responses:
        "200":
          description: User ID and comma separated roles
          schema:
            type: body
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
  /api/v1/auth/signup:
    post:
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
  /api/v1/users/{id}:
    get:
      consumes:
      - application/json
      description: Create new session or continue old one
      operationId: login
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Log user into the system
swagger: "2.0"
