// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package csat_microservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CSATQuestionServiceClient is the client API for CSATQuestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CSATQuestionServiceClient interface {
	CheckRating(ctx context.Context, in *CheckRatingRequest, opts ...grpc.CallOption) (*CheckRatingResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type cSATQuestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCSATQuestionServiceClient(cc grpc.ClientConnInterface) CSATQuestionServiceClient {
	return &cSATQuestionServiceClient{cc}
}

func (c *cSATQuestionServiceClient) CheckRating(ctx context.Context, in *CheckRatingRequest, opts ...grpc.CallOption) (*CheckRatingResponse, error) {
	out := new(CheckRatingResponse)
	err := c.cc.Invoke(ctx, "/CSATQuestionService/CheckRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cSATQuestionServiceClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/CSATQuestionService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cSATQuestionServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, "/CSATQuestionService/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cSATQuestionServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/CSATQuestionService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cSATQuestionServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/CSATQuestionService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cSATQuestionServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/CSATQuestionService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CSATQuestionServiceServer is the server API for CSATQuestionService service.
// All implementations must embed UnimplementedCSATQuestionServiceServer
// for forward compatibility
type CSATQuestionServiceServer interface {
	CheckRating(context.Context, *CheckRatingRequest) (*CheckRatingResponse, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedCSATQuestionServiceServer()
}

// UnimplementedCSATQuestionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCSATQuestionServiceServer struct {
}

func (UnimplementedCSATQuestionServiceServer) CheckRating(context.Context, *CheckRatingRequest) (*CheckRatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRating not implemented")
}
func (UnimplementedCSATQuestionServiceServer) GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedCSATQuestionServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedCSATQuestionServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCSATQuestionServiceServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCSATQuestionServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCSATQuestionServiceServer) mustEmbedUnimplementedCSATQuestionServiceServer() {}

// UnsafeCSATQuestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CSATQuestionServiceServer will
// result in compilation errors.
type UnsafeCSATQuestionServiceServer interface {
	mustEmbedUnimplementedCSATQuestionServiceServer()
}

func RegisterCSATQuestionServiceServer(s grpc.ServiceRegistrar, srv CSATQuestionServiceServer) {
	s.RegisterService(&CSATQuestionService_ServiceDesc, srv)
}

func _CSATQuestionService_CheckRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSATQuestionServiceServer).CheckRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CSATQuestionService/CheckRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSATQuestionServiceServer).CheckRating(ctx, req.(*CheckRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CSATQuestionService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSATQuestionServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CSATQuestionService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSATQuestionServiceServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CSATQuestionService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSATQuestionServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CSATQuestionService/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSATQuestionServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CSATQuestionService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSATQuestionServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CSATQuestionService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSATQuestionServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CSATQuestionService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSATQuestionServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CSATQuestionService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSATQuestionServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CSATQuestionService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSATQuestionServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CSATQuestionService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSATQuestionServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CSATQuestionService_ServiceDesc is the grpc.ServiceDesc for CSATQuestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CSATQuestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CSATQuestionService",
	HandlerType: (*CSATQuestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckRating",
			Handler:    _CSATQuestionService_CheckRating_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _CSATQuestionService_GetAll_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _CSATQuestionService_GetStats_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _CSATQuestionService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CSATQuestionService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CSATQuestionService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "csat/api/csat_question.proto",
}
